from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(320, 153)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(320, 153))
        Dialog.setMaximumSize(QtCore.QSize(320, 153))
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_brightess = QtWidgets.QLabel(Dialog)
        self.label_brightess.setObjectName("label_brightess")
        self.verticalLayout.addWidget(self.label_brightess)
        self.horizontalSlider_brightess = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_brightess.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_brightess.setMinimum(-128)
        self.horizontalSlider_brightess.setMaximum(128)
        self.horizontalSlider_brightess.setProperty("value", 0)
        self.horizontalSlider_brightess.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_brightess.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_brightess.setTickInterval(10)
        self.horizontalSlider_brightess.setObjectName("horizontalSlider_brightess")
        self.verticalLayout.addWidget(self.horizontalSlider_brightess)
        self.label_contrast = QtWidgets.QLabel(Dialog)
        self.label_contrast.setObjectName("label_contrast")
        self.verticalLayout.addWidget(self.label_contrast)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalSlider_contrast = QtWidgets.QSlider(Dialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.horizontalSlider_contrast.setFont(font)
        self.horizontalSlider_contrast.setMouseTracking(False)
        self.horizontalSlider_contrast.setTabletTracking(False)
        self.horizontalSlider_contrast.setAcceptDrops(False)
        self.horizontalSlider_contrast.setMinimum(10)
        self.horizontalSlider_contrast.setMaximum(190)
        self.horizontalSlider_contrast.setProperty("value", 100)
        self.horizontalSlider_contrast.setTracking(True)
        self.horizontalSlider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_contrast.setInvertedAppearance(False)
        self.horizontalSlider_contrast.setInvertedControls(False)
        self.horizontalSlider_contrast.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_contrast.setTickInterval(10)
        self.horizontalSlider_contrast.setObjectName("horizontalSlider_contrast")
        self.verticalLayout.addWidget(self.horizontalSlider_contrast)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.checkBox = QtWidgets.QCheckBox(self.splitter)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.splitter)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Brighthess-Contrast"))
        self.label_brightess.setText(_translate("Dialog", "Brighthess:"))
        self.label_contrast.setText(_translate("Dialog", "Contrast:"))
        self.checkBox.setText(_translate("Dialog", "Preview"))
