from PyQt5 import QtCore, QtGui, QtWidgets


class Main_Menu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Label_Image = QtWidgets.QLabel(self.groupBox)
        self.Label_Image.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Image.setObjectName("Label_Image")
        self.verticalLayout_2.addWidget(self.Label_Image)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Slider_Brightness = QtWidgets.QSlider(self.centralwidget)
        self.Slider_Brightness.setAccessibleDescription("")
        self.Slider_Brightness.setMaximum(255)
        self.Slider_Brightness.setMinimum(-255)
        self.Slider_Brightness.setSingleStep(1)
        self.Slider_Brightness.setProperty("value", 0)
        self.Slider_Brightness.setOrientation(QtCore.Qt.Vertical)
        self.Slider_Brightness.setObjectName("Slider_Brightness")
        self.horizontalLayout_5.addWidget(self.Slider_Brightness)
        self.Slider_Contrast = QtWidgets.QSlider(self.centralwidget)
        self.Slider_Contrast.setMaximum(100)
        self.Slider_Contrast.setMinimum(0)
        self.Slider_Contrast.setSingleStep(1)
        self.Slider_Contrast.setProperty("value", 0)
        self.Slider_Contrast.setOrientation(QtCore.Qt.Vertical)
        self.Slider_Contrast.setObjectName("Slider_Contrast")
        self.horizontalLayout_5.addWidget(self.Slider_Contrast)
        # self.Slider_Sharpness = QtWidgets.QSlider(self.centralwidget)
        # self.Slider_Sharpness.setMaximum(255)
        # self.Slider_Sharpness.setMinimum(-255)
        # self.Slider_Sharpness.setSingleStep(1)
        # self.Slider_Sharpness.setProperty("value", 0)
        # self.Slider_Sharpness.setOrientation(QtCore.Qt.Vertical)
        # self.Slider_Sharpness.setObjectName("Slider_Sharpness")
        # self.horizontalLayout_5.addWidget(self.Slider_Sharpness)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Height = QtWidgets.QLabel(self.centralwidget)
        self.Label_Height.setObjectName("Label_Height")
        self.horizontalLayout.addWidget(self.Label_Height)
        self.spinBox_Height = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Height.setMaximum(1024)
        self.spinBox_Height.setObjectName("spinBox_Height")
        self.horizontalLayout.addWidget(self.spinBox_Height)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Label_Width = QtWidgets.QLabel(self.centralwidget)
        self.Label_Width.setObjectName("Label_Width")
        self.horizontalLayout_2.addWidget(self.Label_Width)
        self.spinBox_Width = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Width.setMaximum(1024)
        self.spinBox_Width.setObjectName("spinBox_Width")
        self.horizontalLayout_2.addWidget(self.spinBox_Width)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.checkBox_Square = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Square.setChecked(True)
        self.checkBox_Square.setObjectName("checkBox_Square")
        self.horizontalLayout_3.addWidget(self.checkBox_Square)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Label_ColorMode = QtWidgets.QLabel(self.centralwidget)
        self.Label_ColorMode.setObjectName("Label_ColorMode")
        self.horizontalLayout_7.addWidget(self.Label_ColorMode)
        self.comboBox_ColorMode = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ColorMode.setObjectName("comboBox_ColorMode")
        self.comboBox_ColorMode.addItem("")
        self.comboBox_ColorMode.addItem("")
        self.comboBox_ColorMode.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_ColorMode)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        self.checkBox_Compression = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Compression.setObjectName("checkBox_Compression")
        self.horizontalLayout_4.addWidget(self.checkBox_Compression)
        self.Label_FileSize = QtWidgets.QLabel(self.centralwidget)
        self.Label_FileSize.setStyleSheet("")
        self.Label_FileSize.setObjectName("Label_FileSize")
        self.horizontalLayout_4.addWidget(self.Label_FileSize)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.Button_Convert = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Convert.setObjectName("Button_Convert")
        self.horizontalLayout_4.addWidget(self.Button_Convert)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        # self.actionSave = QtWidgets.QAction(MainWindow)
        # self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setShortcut("")
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen)
        #self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "E2img - img2eimg"))
        self.groupBox.setTitle(_translate("MainWindow", "Preview"))
        # self.Label_Image.setText(_translate("MainWindow", ""))
        self.Slider_Brightness.setToolTip(_translate("MainWindow", "Brightness"))
        self.Slider_Contrast.setToolTip(_translate("MainWindow", "Сontrast"))
        # self.Slider_Sharpness.setToolTip(_translate("MainWindow", "Sharpness"))
        self.Label_Height.setText(_translate("MainWindow", "Height:"))
        self.spinBox_Height.setSuffix(_translate("MainWindow", " px"))
        self.Label_Width.setText(_translate("MainWindow", "Width:"))
        self.spinBox_Width.setSuffix(_translate("MainWindow", " px"))
        self.checkBox_Square.setToolTip(_translate("MainWindow", "Makes the image square."))
        self.checkBox_Square.setText(_translate("MainWindow", "Square image"))
        self.Label_ColorMode.setText(_translate("MainWindow", "Color mode:"))
        self.comboBox_ColorMode.setItemText(0, _translate("MainWindow", "24 Bit (Recommended)"))
        self.comboBox_ColorMode.setItemText(1, _translate("MainWindow", "RRRGGGBBB"))
        self.comboBox_ColorMode.setItemText(2, _translate("MainWindow", "RGBXXX"))
        self.checkBox_Compression.setToolTip(_translate("MainWindow", "Automatic file compression. Reduces the performance of Expression 2. It is not recommended to use."))
        self.checkBox_Compression.setText(_translate("MainWindow", "Auto compression"))
        self.Label_FileSize.setText(_translate("MainWindow", "File Size: 315 Kb"))
        self.Button_Convert.setToolTip(_translate("MainWindow", "Converts a file to a special format for Expression 2"))
        self.Button_Convert.setText(_translate("MainWindow", "Convert"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setIconText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        # self.actionSave.setText(_translate("MainWindow", "Save"))
        # self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
